drop table if exists shopping_list;

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER primary key generated by default as identity not null,
    itemName TEXT not null,
    price DECIMAL (12, 2) not null,
    dateAdded TIMESTAMP default now() not null,
    checked BOOLEAN default 'False' not null,
    category grocery not null 
);