BEGIN;

INSERT INTO blogful_articles
    (title, date_published, content)

VALUES
    ('A Type Of Chimp You Can Take To Work',    '2016-01-01 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Bret Stephens is a Dummy',                '2017-02-02 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Clever: Human Dumpster Eats Seafood',     '2018-03-03 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Humans Should Never Go In The Car Wash',  '2019-04-04 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('My Dog Is Louder Than Your Dog',          '2017-05-05 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Klonopin Jonathan Strikes Again',         '2016-06-06 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Morgenthau Laundromat Axiom Dresser',     '2015-07-07 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Types of Chickens For The Rustic Life',   '2014-08-08 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('A Man Is Just A Dog Wearing Pants',       '2013-09-09 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Noodler Stevens Noodle Torture',          '2012-10-10 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('An Uncle By Any Other Name',              '2013-11-11 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Time To Talk About TV Movies',            '2014-12-12 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('O Brother Where Art Houston',             '2015-01-13 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Clocks I Own In My House',                '2016-02-14 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Uber Is Lyft For Dummies',                '2017-03-15 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Heres A Blog Post: Shut Up',              '2018-04-16 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Murder Should Be Legal And Heres Why',    '2019-05-17 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('The Morse Code Murders',                  '2018-06-18 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Shut Up: A Blog Post',                    '2017-07-19 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.'),
    ('Hamburger Lamburger',                     '2016-08-20 12:00:00',  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus hendrerit orci vel lobortis. Nulla lacinia gravida semper. Suspendisse imperdiet leo at nisi finibus efficitur. Ut convallis posuere orci sed tempus. Quisque finibus ultricies imperdiet. Aenean finibus tortor dolor, quis luctus turpis lacinia vel. Donec condimentum varius ipsum. Phasellus convallis, tortor ac dignissim molestie, justo ante ultrices mauris, sit amet mattis mauris tellus in sapien. Aliquam sed diam vel erat elementum porttitor at tristique felis.');

    COMMIT;